export const Type = {
    SELECT_TITLE: 'SELECT_TITLE',
    INVALIDATE_TITLE: 'INVALIDATE_TITLE',
    SUCCESS_REQUEST: 'SUCCESS_REQUEST',
    FAIL_REQUEST: 'FAIL_REQUEST',
    START_REQUEST: 'START_REQUEST'
}